server:
  port: 8093
  
spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa: 
    hibernate:
      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789012

--- 

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test 
    
---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/eatgo?characterEncoding=UTF-8&serverTimezone=UTC
    username: motiveko
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      